---
abstract: 'FileHandle which supports multi-byte unget'
author:
  - 'David Coppit <david@coppit.org>.'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Spec::Functions: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: FileHandle::Unget
name: FileHandle-Unget
no_index:
  directory:
    - inc
    - t
requires:
  Scalar::Util: '1.14'
  perl: '5.005'
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '0.1624'
